-- TEMPORAL: Deshabilitar RLS para testing
-- ⚠️ SOLO PARA DESARROLLO - VOLVER A HABILITAR EN PRODUCCIÓN

ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE aplicantes DISABLE ROW LEVEL SECURITY;

-- Para volver a habilitarlo después:
-- ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE aplicantes ENABLE ROW LEVEL SECURITY;